# Generated by Django 3.2 on 2021-07-05 07:53

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone_number',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True),
        ),
    ]
