# Generated by Django 3.2 on 2021-07-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_useraccount_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordTable',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
