# Generated by Django 3.2 on 2021-07-07 07:11

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_resetpasswordtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtable',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
